[package]
edition = "2021"
name = "abi-checker"
version = "0.1.0"

[dependencies]
built = "0.5.1"
cc = "1.0.73"
clap = { version = "3.1.6", features = ["cargo", "wrap_help"] }
libloading = "0.7.3"
log = "0.4.14"
ron = "0.7.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.83"
simplelog = "0.11.2"
thiserror = "1.0.30"


[build-dependencies]
built = "*"
